global:
  scrape_interval: 5s
scrape_configs:
  - job_name: triton
    static_configs:
      - targets: ["inference-1:8002", "inference-2:8002"]
  - job_name: nginx
    static_configs:
      - targets: ["nginx-exporter:9113"]
  - job_name: dcgm
    static_configs:
      - targets: ["dcgm-exporter:9400"]
